---
title       : Engage pitch August 2016
subtitle    : 
author      : Ryan Conger
job         : 
framework   : impressjs        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

--- .slide x:-1000 y:-1500

<q>**Life After Edison**</q>

Ryan Conger

August 2016

--- .slide x:0 y:-1500

<q>**Messages**</q>
<q>If things don't go your way, that usually ends up being a good thing
Make the effort to learn about yourself</q>
* There's more to life than just work

--- .slide x:1000 y:-1500

<q>Who am I?</q>

<q>Ryan Conger</q>
* Technical Leader, Lifing Analytics
* Power Services
* EEDP class of 2009
* Left GE for a startup

--- #careertitle x:500 y:500 scale:3

<q>My Career (so far)</q>

--- #phase1 x:0 y:1000 scale:1

<b>2007-2009: GE Energy</b>

## Edison Program

* Gas Turbine Hot Gas Path (HGP) Repair [Greenville, SC]
* Gas Turbine Systems Engineer [Greeville, SC]
* Bently Nevada Design Engineer [Minden, NV]
* Bently Nevada Machinery Diagnostics Engineer [Minden, NV]

--- #phase2 x:0 y:1500 scale:1

End of 2009: <b class="positioning">left GE</b>
<b>2009-2011: Synapse Product Development</b>

--- #phase3 x:0 y:2000 scale:1

<b>2011-2015: GE Oil & Gas, Bently Nevada</b>

--- #phase4 x:0 y:2500 scale:1

<b>2011-2015: GE Power, Power Services</b>

--- #not x:-1700 y:1500 scale:3

But that's not 
the whole story.

--- #big x:4500 y:2100 rot:180 scale:4

so many things <b>didn't</b> <span class="thoughts">how I expected</span>

--- #tiny x:3925 y:2325 z:-3000 rot:300 scale:1

and that turned out to actually be a good thing.

--- #ing x:3500 y:-850 rot:270 scale:6
the <b class="positioning">obstacles</b>, <b class="rotating">failures</b> and <b class="scaling">changes</b> all contribute to the person I am today.

--- #phase1notes x:1000 y:5000 scale:1 rot:180

<b>2007-2009: Edison Program</b>

* Wanted to come off program in Nevada. No available jobs.

--- #phase2notes x:1000 y:4750 scale:1 rot:180

End of 2009: <b class="positioning">left GE</b>

* Thought a startup would fit me well. The intensity, travel (and weather) was too much for me.

--- #phase2anotes x:1000 y:4500 scale:1 rot:180

<b>2009-2011: Synapse</b>

* Interviewed for a 'dream job' (didn't get it). 

--- #phase3notes x:1000 y:4000 scale:1 rot:180

<b>2011-2015: GE Oil & Gas, Bently Nevada</b>

* Sought life/work balance.
* Swung far to the life side of that balance and missed growth at work.
* Applied for team lead (didn't get it).

--- #phase4notes x:1000 y:3500 scale:1 rot:180

<b>2015: Moved from Oil & Gas (NV) to Power (SC)</b>

* Lived next to a ski resort. Moved back east to start a family and grow in other ways.

--- #imagination x:6700 y:-300 scale:6

the only **limit** is your <b class="imagination">imagination</b>

--- #one-more-thing x:6000 y:4000 scale:2

one more thing...

--- #rstats x:-1000 y:5000

This deck was built using [Slidify](http://www.slidify.org) and styled with [impress.js](http://github.com/bartaz/impress.js). [View the source](http://github.com/bartaz/impress.js), Luke</q>



